version: "3.9"
networks:
  leantime:
      external: false
      driver: bridge
volumes:
  mysql:
  s3ninja-data:

services:
  leantime-dev:
    privileged: true
    build: .
    ports:
      - "8090:8080"
    volumes:
     - "../:/var/www/html"
     - "./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
     - "./error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini"
     - ".env:/var/www/html/config/.env"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - leantime
  
  samba-dc:
    privileged: true
    build: ./samba
    extra_hosts:
      - "host.docker.internal:host-gateway"
    hostname: ad.leantime.dev
    expose:
     - 636
    environment:
      - SMB_ADMIN_PASSWORD=admin123!
    networks:
      - leantime
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: leantime
      MYSQL_USER: leantime
      MYSQL_PASSWORD: leantime
      MYSQL_DATABASE: leantime
    networks:
      - leantime
    volumes:
      - mysql:/var/lib/mysql:rw
    healthcheck:
      test: "mysql -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SELECT 1'"
      interval: 5s
      timeout: 5s
      retries: 20
  maildev:
    image: maildev/maildev
    environment:
      - MAILDEV_SMTP_PORT=465
      - MAILDEV_WEB_PORT=8081
    ports:
      - 8081:8081
    networks:
      - leantime
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8082:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - leantime
  s3ninja:
    image: scireum/s3-ninja
    ports:
      - 8083:9000
    networks:
      - leantime
    volumes:
      - s3ninja-data:/home/sirius/data
