FROM ubuntu:22.04
 
RUN DEBIAN_FRONTEND=noninteractive apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install samba krb5-config winbind smbclient 
RUN DEBIAN_FRONTEND=noninteractive apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install iproute2
RUN DEBIAN_FRONTEND=noninteractive apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install openssl
RUN DEBIAN_FRONTEND=noninteractive apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install vim
 
RUN rm /etc/krb5.conf
RUN mkdir -p /opt/ad-scripts
 
WORKDIR /opt/ad-scripts
COPY *.sh /opt/ad-scripts
COPY ldap.conf /etc/ldap/ldap.conf

RUN chmod +x /opt/ad-scripts/*.sh

ENTRYPOINT /opt/ad-scripts/samba-ad-setup.sh && /opt/ad-scripts/samba-ad-run.sh
