when:
  - event: push
    branch: "chore/frankenphp-conversion"
clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      depth: 10
      lfs: false
      submodule-override:
        "app/Plugins": https://github.com/Leantime/plugins.git

steps:
  - name: Build Leantime for multiple platforms
    image: woodpeckerci/plugin-docker-buildx:6.0.0
    settings:
      registry: http://registry.kisoft.me/v2
      repo: registry.kisoft.me/leantime
      platforms: linux/386,linux/arm/v7,linux/arm64,linux/amd64
      dockerfile: .docker/franken.dockerfile
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password